# This file will contain a script in orde to start up the system (all microservices) 
version: '3.4'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
    frontend:
        build: ./frontend-web/contentbeheer-frontend
        ports:
            - "80:80"
